# Generated by Django 4.2.7 on 2023-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('PNG', 'Png'), ('JPG', 'Jpg'), ('JPEG', 'Jpeg'), ('PDF', 'Pdf'), ('DOCX', 'Docx'), ('WEBP', 'Webp'), ('MP4', 'Mp4'), ('WMV', 'Wmv'), ('MKV', 'Mkv'), ('OTHER', 'Other')], default='OTHER'),
        ),
    ]
