# Generated by Django 4.2.2 on 2023-06-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_notes_created_notes_updated_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='average',
            field=models.IntegerField(help_text='What is the average score of the flashcard. After every lapse, the score is added', null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='lapses',
            field=models.IntegerField(default=0, help_text='How many times has the flashcard been reviewed'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='score',
            field=models.IntegerField(default=0, help_text='How much score is gained by the card', null=True),
        ),
    ]
