# Generated by Django 4.2.2 on 2023-06-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_notes_title_alter_flashcard_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='flashcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcard.flashcard'),
        ),
    ]
