# Generated by Django 4.2.2 on 2023-06-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0009_alter_notes_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefers_dark_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcard.topics'),
        ),
    ]
