# Generated by Django 4.2.2 on 2023-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0011_alter_user_prefers_dark_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefers_dark_theme',
            new_name='prefer_dark_theme',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If the person is active, it is True'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
