# Generated by Django 4.2.2 on 2023-06-16 02:57

from django.db import migrations
import flashcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0013_subject_creator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', flashcard.models.UserManager()),
            ],
        ),
    ]
