# Generated by Django 4.2.2 on 2023-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0016_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the person is active, it is True'),
        ),
    ]
