# Generated by Django 4.2.2 on 2023-06-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0017_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar/avatar.png', null=True, upload_to=''),
        ),
    ]
