# Generated by Django 4.2.2 on 2023-06-16 23:25

from django.db import migrations, models
import flashcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0018_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=flashcard.models.get_default_avatar, null=True, upload_to=''),
        ),
    ]
