# Generated by Django 4.2.2 on 2023-06-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='accomplished',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_accomplished',
        ),
    ]
