# Generated by Django 4.2.2 on 2023-06-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0021_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='picture',
            field=models.ImageField(default='related/head_icon/android-chrome-512x512.png', null=True, upload_to=''),
        ),
    ]
