# Generated by Django 4.2.2 on 2023-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0022_alter_subject_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='picture',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
