# Generated by Django 4.2.2 on 2023-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0023_alter_subject_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer_preview',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_preview',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
