# Generated by Django 4.2.2 on 2023-06-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0024_flashcard_answer_preview_flashcard_question_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer_preview',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question_preview',
        ),
    ]
