# Generated by Django 4.2.2 on 2023-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0025_remove_flashcard_answer_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
