# Generated by Django 4.2.2 on 2023-06-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0026_alter_subject_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='average',
            field=models.IntegerField(default=0, help_text='What is the average score of the flashcard. After every lapse, the score is added', null=True),
        ),
    ]
