# Generated by Django 4.2.2 on 2023-06-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0027_alter_flashcard_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='average',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='lapses',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='score',
        ),
    ]
