# Generated by Django 4.2.2 on 2023-06-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0028_remove_flashcard_average_remove_flashcard_lapses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
