# Generated by Django 4.2.2 on 2023-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0029_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/avatar.png', null=True, upload_to=''),
        ),
    ]
