# Generated by Django 4.2.2 on 2023-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0030_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='custom_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/avatar/avatar.png', null=True, upload_to=''),
        ),
    ]
