# Generated by Django 4.2.2 on 2023-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0031_alter_friendship_custom_name_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
