# Generated by Django 4.2.2 on 2023-06-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0032_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_last_message', to='flashcard.groupmessages'),
        ),
    ]
