# Generated by Django 4.2.2 on 2023-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0033_group_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
