# Generated by Django 4.2.2 on 2023-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0034_alter_groupmessages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='message',
            field=models.CharField(help_text='Message', max_length=1000),
        ),
    ]
