# Generated by Django 4.2.2 on 2023-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0036_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='picture',
            field=models.ImageField(blank=True, default='#', null=True, upload_to=''),
        ),
    ]
