# Generated by Django 4.2.2 on 2023-06-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0037_alter_subject_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='picture',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='image/avatar'),
        ),
    ]
