# Generated by Django 4.2.7 on 2023-11-22 11:02

from django.db import migrations, models
import flashcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0038_alter_subject_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='biography',
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default=flashcard.models.get_default_group_avatar, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=flashcard.models.get_default_avatar, null=True, upload_to=''),
        ),
    ]
