# Generated by Django 4.2.7 on 2023-11-23 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0040_file_tag_alter_user_education_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files'),
            preserve_default=False,
        ),
    ]
